#leave /tmp and /opt/jumpscale8 in this file, gets replaced during installation

[main]
max_jobs = 524288
include = ["/etc/g8os/conf"]
log_level = "info"
network = "/etc/g8os/network.toml"

[sink.main]
url = "redis://127.0.0.1:6379"
password = ""

[logging]
    [logging.console]
    type = "console"
    levels = [2, 4, 7, 8, 9]

    [logging.redis]
    type = "redis"
    levels = [1, 2, 4, 7, 8, 9]
    address = "127.0.0.1:6379"
    batch_size = 1000

[stats]
interval = 60000 # milliseconds (1 min)

[stats.redis]
enabled = true
flush_interval = 1 # second
address = "127.0.0.1:6379"

[globals]
storage = "ardb://hub.gig.tech:16379"
