#leave /tmp and /opt/jumpscale8 in this file, gets replaced during installation

[main]
max_jobs = 524288
include = ["/etc/g8os/conf"]
log_level = "info"
network = "/etc/g8os/network.toml"

[containers]
max_count = 1000

[logging.file]
levels = [2, 4, 7, 8, 9]

[logging.ledis]
levels = [1, 2, 4, 7, 8, 9]
size = 10000 # how many log lines to keep in ledis

[stats]
enabled = true
flush_interval = 1 # seconds

[globals]
storage = "ardb://hub.gig.tech:16379"
