[startup.modprobe]
name = "bash"
after = ["init"]
running_delay = -1

[startup.modprobe.args]
stdin = """

# load all required hardware modules here
echo 'Loading kernel modules'
modprobe e1000e
modprobe e1000
modprobe e100
"""

