[startup.udevd]
name = "core.system"
after = ["init"]

[startup.udevd.args]
name = "udevd"
args = ["--daemon"]

[startup.udevtrigger]
name = "bash"
after = ["init"]
running_delay = -1

[startup.udevtrigger.args]
script = """
udevadm trigger --action=add; udevadm settle
"""
